---
#HttpServer:
#  ServiceSetting:
#    ServiceBindIP: "0.0.0.0"
#    ServicePort: 8080
#    ServiceLogPath: "./logs/httpServer.log"

HttpServer:
  ServiceSetting:
    bindIP: "0.0.0.0"
    port: 8080
    logPath: "./logs/httpServer.log"
